development:
  adapter: postgresql
  encoding: unicode
  database: angular_api
  pool: 5
  username: postgres
  password: postgres

test:
 adapter: postgresql
 encoding: unicode
 database: angular_api
 pool: 5
 username: postgres
 password: postgres